networks:
  default:
    name: opentelemetry-example
    driver: bridge

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4317   # OTLP gRPC receiver
      - "16686:16686" # UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true
